config/routes.rb
Rails.application.routes.draw do
  
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get '/message' => 'pages#display_message', as: 'display_message'
  get '/new' => 'pages#new', as: 'new_message'
  get '/login' => 'pages#login', as: 'login'
  get '/sent' => 'pages#sent', as: 'sent'
  post '/send' => 'pages#send_message', as: 'send_message'
  

  resources :sessions, only: [:create, :destroy]
  root to: 'pages#index'

end

app/models/upload.rb
class Upload < ActiveRecord::Base
    mount_uploader :avatar, AvatarUploader
    
    validates :avatar, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.image = auth.info.image
      user.oauth_refresh_token = auth.credentials.refresh_token if auth.credentials.refresh_token
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  add_flash_types :success, :failure
  rescue_from Net::IMAP::BadResponseError, with: :logout

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] rescue ""
  end

  def logout
    redirect_to signout_path, failure: "User account timed out. Log in again to continue.", success: ""
  end
end

app/controllers/pages_controller.rb
require 'will_paginate/array'

class PagesController < ApplicationController
  before_action :set_account

  def index
    if !current_user.blank?
      @read_count = @gmail.inbox.emails(:read).count
      @unread_count = @gmail.inbox.emails(:unread).count
      @read = @gmail.inbox.emails(:read).reverse!.paginate(:page => params[:read_page], :per_page => 10)
      @unread = @gmail.inbox.emails(:unread).reverse!.paginate(:page => params[:unread_page], :per_page => 10)
    else
      render "login", :layout => "login_layout"
    end
  end

  def sent
    if !current_user.blank?
      @read_count = @gmail.mailbox('sent').emails(:read).count
      @unread_count = @gmail.mailbox('sent').emails(:unread).count
      @read = @gmail.mailbox('sent').emails(:read).reverse!.paginate(:page => params[:read_page], :per_page => 10)
      @unread = @gmail.mailbox('sent').emails(:unread).reverse!.paginate(:page => params[:unread_page], :per_page => 10)
    else
      render "login", :layout => "login_layout"
    end
  end

  def login
  end

  def new
  end

  def display_message
    @id = params[:id]
    @mailbox = params[:mailbox]
  end

  def send_message
    params = message_params
    if !params[:file].blank?
      u = Upload.create(avatar: params[:file])
      u.save!
      path = "#{Rails.root}" << "/public" << u.avatar.url
    end

    if (!(params[:cc].blank? && params[:bcc].blank? && params[:to].blank?))
      email = @gmail.compose do
        to "#{params[:to]}" unless params[:to].blank?
        cc "#{params[:cc]}" unless params[:cc].blank?
        bcc "#{params[:bcc]}" unless params[:bcc].blank?
        subject "#{params[:subject]}"
        text_part do
            body "#{params[:message]}"
        end
        html_part do
            body "#{params[:message]}"
        end
        add_file "#{path}" unless path.blank?
      end
      email.deliver!

      Upload.destroy_all
      redirect_to root_path, success: 'Message sent!'
    else
      redirect_to new_message_path, failure: "Error empty recipient."
    end
  end

  def message_params
    params.permit(:utf8, :authenticity_token, :commit, :to, :subject, :message, :file, :cc, :bcc)
  end

  def set_account
    unless current_user.blank?
      @gmail = Gmail.connect(:xoauth2, current_user.email, current_user.oauth_token)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path, success: "You have successfully logged in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, success: "You have successfully logged out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proto-Mailer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class = 'color-layout'>
  <div class = 'container'>
    <nav class="navbar navbar-fixed-top navbar-default color-adish">
      <div class = 'navbar-header'>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
        </button>
        <%= link_to 'Proto-Mailer', root_path,  class: 'navbar-brand'%>
      </div>
      
      <% if !current_user.blank? %>
      <div class = 'collapse navbar-collapse pull-right' style = 'border: none;'>
        <div class = 'nav navbar-nav'>
        <li class = 'nav-item <%= "active" if current_page?(root_path) %>'><%= link_to 'Inbox', root_path,  class: 'navbar-brand navigation-item' %></li>
        <li class = 'nav-item <%= "active" if current_page?(sent_path) %>'><%= link_to 'Sent', sent_path,  class: 'navbar-brand navigation-item' %></li>
        <li class = 'nav-item <%= "active" if current_page?(new_message_path) %>'><%= link_to 'Compose Message', new_message_path,  class: 'navbar-brand navigation-item' %></li>
        <li class = 'nav-item'>
          <div class="dropdown pull-right navigation-dropdown">
            <button class="btn btn-primary dropdown-toggle navigation-button"
                    type="button" id="dropdownMenu4" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false" style = 'padding-bottom: 15px; padding-top: 15px; border: none; background-color: #ff7300'>
              <%= current_user.name.upcase %> <b class = 'caret'></b>
            </button>
            <ul class="dropdown-menu">
              <li><%= link_to signout_path, id: "sign_out", class: 'dropdown-item text-center' do %>
                     SIGN OUT <%= fa_icon 'sign-out'%>
                  <% end %>
              </li>
            </ul>
          </div>
        </li>
        </div>
      </div>    
    <% end %>
    </nav>
  </div>
  <div class = 'container app-content'>
  <% if failure %>
    <div class = 'pull-right alert alert-dismissible alert-danger topright'>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
      </button>
      <%= failure %>
    </div>
  <% end %>
  <% if success %>
    <div class = 'pull-right alert alert-dismissible alert-success topright'>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
      </button>
      <%= success %>
    </div>
  <% end %>
  <%= yield %>
  </div>
</body>
</html>

app/views/layouts/login_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proto-Mailer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class = 'color-layout'>
  <div class = 'container'>
    <% if failure %>
    <div class = 'pull-right alert alert-dismissible alert-danger'>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
      </button>
      <%= failure %>
    </div>
    <% end %>
    <% if success %>
      <div class = 'pull-right alert alert-dismissible alert-success'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <%= success %>
      </div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/pages/display_message.html.erb
  <% email = @gmail.inbox.find(uid: @id).pop if @mailbox == 'inbox' %>
  <% email = @gmail.mailbox('sent').find(uid: @id).pop if @mailbox == 'sent' %>

  <% if !email.blank? %>

    <% email.read! %>

    <% subject = email.message.subject %>
    <% if !subject.blank? %>
      <% if subject.include? "=?WINDOWS-1252?Q?" %>
      <% subject = subject.gsub!("=?WINDOWS-1252?Q?","").unpack("M").first.gsub('_',' ').force_encoding('WINDOWS-1252').encode('UTF-8')%>
      <% end %>
    <% else %>
      <% subject = "(No Subject)" %>
    <% end %>
    <% sender = email.from[0].mailbox << "@" << email.from[0].host%>

    <% if email.message.html_part.present? %>
        <% message = /<img src=('|")cid:([\w\W]+?)('|")>/.match(email.message.html_part.decoded) ? email.message.html_part.decoded.gsub(/<img src=('|")cid:([\w\W]+?)('|")>/, "") : email.message.html_part.decoded rescue email.message.decoded %>
      <% elsif email.message.text_part.present? %>
        <% message = /<img src=('|")cid:([\w\W]+?)('|")>/.match(email.message.text_part.decoded) ? email.message.text_part.decoded.gsub(/<img src=('|")cid:([\w\W]+?)('|")>/, "") : email.message.text_part.decoded %>
      <% else %>
        <% message = /<img src=('|")cid:([\w\W]+?)('|")>/.match(email.raw_message.body.decoded) ? email.raw_message.body.decoded.gsub(/<img src=('|")cid:([\w\W]+?)('|")>/, "") : email.raw_message.body.decoded %>
    <% end %>

    <div class = 'row center-block'>
      <span>Sent By: <%= sender %></span><br>
      <span>Subject: <%= subject %></span>
    </div>
    <br>
    <div class = 'row center-block scroll-content'>
      <div class = 'col-lg-12 col-md-12 col-sm-12 col-xs-12'>
        <%= message.html_safe %>
      </div>
      <br><br>
      <% if email.multipart? %>
          <% unless email.message.attachments.empty? %>
            <div class = 'col-lg-12 col-md-12 col-sm-12 col-xs-12'>
              <span>This message has the following attached files:</span>
            </div>
            <% folder = Rails.root.join('public', 'uploads', 'file_uploads')%>
             <% email.message.attachments.each do |f| %>
               <% File.write(File.join(folder, f.filename), f.body.decoded.force_encoding('utf-8')) %>
                 <% if f.content_type.include?("image/jpeg") || f.content_type.include?("image/gif") || f.content_type.include?("image/png") %>
                   <% file = File.open(File.join("#{folder}", "#{f.filename}")) %>
                   <% u = Upload.create(avatar: file) %>
                   <% if /attachment/.match(f.content_disposition) %>
                   <div class = 'col-lg-2 col-md-2 col-sm-2 col-xs-2 data'>
                     <br>
                <%= image_tag "#{u.avatar.url}", size: "100x100", alt: "#{f.filename}", title: "#{f.filename}" %>
                   <% else %>
                   <div class = 'col-lg-12 col-md-12 col-sm-12 col-xs-12'>
                     <br>
                <%= image_tag "#{u.avatar.url}", alt: "#{f.filename}", title: "#{f.filename}", class: 'display_inline_image' %>
                   <% end %>
                 <% else %>
                 <div class = 'col-lg-12 col-md-12 col-sm-12 col-xs-12'>
                   <br>
                   <%= f.filename %>
                 <% end %>
                 </div>
             <% end %>
           <% end %>
      <% end %>
    </div>

    <hr></hr>
    <div class = 'row center-block'>
    <%= form_tag(send_message_path) do %>
      <div class = 'form-group'>
          <%= label_tag('to', "To:") %>
          <%= email_field_tag('to', sender, class: 'form-control', required: true) %>
      </div>
      <div class = 'form-group'>
          <%= label_tag('message', "Reply:") %>
          <%= text_area_tag('message', nil, rows: 10, cols: 25, class: 'form-control') %>
      </div>
      <%= submit_tag("Send", class: 'btn btn-primary') %>
    <% end %>
    </div>
  <% else %>
  <div class = 'row center-block'>
    Email not found.
  </div>
  <% end %>

  <br>

app/views/pages/index.html.erb
<% if !current_user.blank? %>

<ul class="nav nav-tabs" id = 'message_navigation'>
  <li class = "active" ><a data-target='#unread_tab' data-toggle="tab" role='tab'>Unread <span class="badge"><%= @unread_count if @unread_count > 0 %></span></a></li>
  <li><a data-target='#read_tab' data-toggle="tab" role='tab'>Read <span class="badge"><%= @read_count if @read_count > 0 %></a></li>
</ul>
      
<div class = 'tab-content'>
<div class = 'clearfix'></div>
<br>
  <div class="tab-pane active" id = 'unread_tab'>

<% if @unread_count > 0 %>
  <% @unread.each do |email| %>
    <%= link_to display_message_path(id: email.uid, mailbox: 'inbox') do%>
    <div class = 'row message-row'>
      <div class = 'col-md-12 col-lg-12 col-xs-12 col-sm-12'>
      
        <% email_sender = email.from[0].mailbox << "@" << email.from[0].host %>
        <% email.from[0].name.blank? ? sender = email_sender :  sender = email.from[0].name %>
        <div class = 'col-lg-4 col-md-4 col-sm-4 col-xs-4 data'>
          <span class = 'data'><%= sender %></span>
        </div>
        <% subject = email.message.subject %>
        <% if !subject.blank? %>
          <% if subject.include? "=?WINDOWS-1252?Q?" %>
          <% subject = subject.gsub!("=?WINDOWS-1252?Q?","").unpack("M").first.gsub('_',' ').force_encoding('WINDOWS-1252').encode('UTF-8')%>
          <% end %>
        <% else %>
          <% subject = "(No Subject)" %>
        <% end %>
        <div class = 'col-lg-6 col-md-6 col-sm-6 col-xs-6 data'>
          <span><%= subject %></span>
        </div>
        <div class = 'col-lg-2 col-md-2 col-sm-2 col-xs-2 data'>
          <% current_date = email.date.to_datetime.in_time_zone("Hong Kong") %>
          <span><%= current_date.to_date.today? ? current_date.strftime('%I:%M %p') : current_date.strftime('%b %e') %></span>
          <% if /Content-Disposition:\s*attachment/.match(email.raw_message.body.decoded) %>
          <span><%= fa_icon 'paperclip' %></span>
          <% end %>
        </div>
      </div>
    </div>  
    <% end %>
  <% end %>
  <%= will_paginate @unread, param_name: 'unread_page',  renderer: BootstrapPagination::Rails %>
<% else %>
  <span>You have no unread messages.</span>
<% end %>
<br>
  </div>
  <div class="tab-pane" id = 'read_tab'>
<% if @read_count > 0 %>
  <% @read.each do |email| %>
    <%= link_to display_message_path(id: email.uid, mailbox: 'inbox') do%>
    <div class = 'row message-row'>
      <div class = 'col-md-12 col-lg-12 col-xs-12 col-sm-12'>
      
        <% email_sender = email.from[0].mailbox << "@" << email.from[0].host %>
        <% email.from[0].name.blank? ? sender = email_sender :  sender = email.from[0].name %>
        <div class = 'col-lg-4 col-md-4 col-sm-4 col-xs-4 data'>
          <span class = 'data'><%= sender %></span>
        </div>
        <% subject = email.message.subject %>
        <% if !subject.blank? %>
          <% if subject.include? "=?WINDOWS-1252?Q?" %>
          <% subject = subject.gsub!("=?WINDOWS-1252?Q?","").unpack("M").first.gsub('_',' ').force_encoding('WINDOWS-1252').encode('UTF-8')%>
          <% end %>
        <% else %>
          <% subject = "(No Subject)" %>
        <% end %>
        <div class = 'col-lg-6 col-md-6 col-sm-6 col-xs-6 data'>
          <span class = 'data'><%= subject %></span>
        </div>
        <div class = 'col-lg-2 col-md-2 col-sm-2 col-xs-2 data'>
          <% current_date = email.date.to_datetime.in_time_zone("Hong Kong") %>
          <span><%= current_date.to_date.today? ? current_date.strftime('%I:%M %p') : current_date.strftime('%b %e') %></span>
          <% if /Content-Disposition:\s*attachment/.match(email.raw_message.body.decoded) %>
          <span><%= fa_icon 'paperclip'  %></span>
          <% end %>
        </div>
      </div>
    </div>  
    <% end %>
  <% end %>
    <%= will_paginate @read, param_name: 'read_page', renderer: BootstrapPagination::Rails %>
    <% else %>
    <span>You have not read any messages.</span>
    <% end %>
  </div>
  <br>
</div>

<script>
    $('#message_navigation a').click(function (e) {
        e.preventDefault()
        $(this).tab('show')
    });

    // store the currently selected tab in the hash value
    $("ul.nav-tabs > li > a").on("shown.bs.tab", function (e) {
        var id = $(e.target).attr("data-target").substr(1);
        window.location.hash = id;
    });

    // on load of the page: switch to the currently selected tab
    var hash = window.location.hash;
    $('#message_navigation a[data-target="' + hash + '"]').tab('show');
</script>
<% end %>

app/views/pages/login.html.erb
<div class="login-page">
  <div class="form">
    <form class="login-form">
      <%= image_tag asset_path('logo.png')%>
      <br><br><br>
      <%= link_to "SIGN IN WITH GOOGLE", "/auth/google_oauth2", id: "sign_in", class: 'btn btn-primary' %>
    </form>
  </div>
</div>

app/views/pages/new.html.erb
<%= form_tag(send_message_path, multipart: true, id: "message_form") do %>
  <div class = 'form-group'>
    <div id = 'error_area'>
    </div>
      <%= label_tag('to', "TO:") %>
      <%= email_field_tag('to', nil, class: 'form-control', multiple: true) %>
      <div class = 'collapse' id = 'cc_field'>
        <%= label_tag('cc', "CC:") %>
        <%= email_field_tag('cc', nil, class: 'form-control', multiple: true) %>
      </div>
      <div class = 'collapse' id = 'bcc_field'>
        <%= label_tag('bcc', "BCC:") %>
        <%= email_field_tag('bcc', nil, class: 'form-control', multiple: true) %>
      </div>

      <br>
      <button type = 'button' id = 'cc_button' class = 'btn btn-default' data-toggle = 'collapse' data-target = '#cc_field'>
        CC:
      </button>
      <button type = 'button' id = 'bcc_button' class = 'btn btn-default' data-toggle = 'collapse' data-target = '#bcc_field'>
        BCC:
      </button>

  </div>

  <div class = 'form-group'>
      <%= label_tag('subject', "Subject:") %>
      <%= text_field_tag('subject', nil, class: 'form-control') %>
  </div>

  <div class = 'form-group'>
      <%= label_tag('message', "Message:") %>
      <%= text_area_tag('message', nil, rows: 10, cols: 25, class: 'form-control') %>
  </div>

  <div id = 'form-group'>
    <label for="file">File to Upload</label>
    <%= file_field_tag "file" %>
  </div>
<br>
  <%= submit_tag("Send", class: 'btn btn-primary') %>
<% end %>
<br>

<script>
  $('#message_form').submit(function(e){
    if ( !$.trim($('#cc').val()) && !$.trim($('#to').val()) && !$.trim($('#bcc').val())){
      e.preventDefault();
      $('#to').css('border-color', 'red');
      $('#error_area').text("Error empty recipient.");
      $('#error_area').css('display', 'block');
    }
  });
</script>

app/views/pages/sent.html.erb
<% if !current_user.blank? %>

<ul class="nav nav-tabs" id = 'message_navigation'>
  <li class = "active" ><a data-target='#unread_tab' data-toggle="tab" role='tab'>Unread <span class="badge"><%= @unread_count if @unread_count > 0 %></span></a></li>
  <li><a data-target='#read_tab' data-toggle="tab" role='tab'>Read <span class="badge"><%= @read_count if @read_count > 0 %></a></li>
</ul>

<div class = 'tab-content'>
<div class = 'clearfix'></div>
<br>
  <div class="tab-pane active" id = 'unread_tab'>

<% if @unread_count > 0 %>
  <% @unread.each do |email| %>
    <%= link_to display_message_path(id: email.uid, mailbox: 'sent') do%>
    <div class = 'row message-row'>
      <div class = 'col-md-12 col-lg-12 col-xs-12 col-sm-12'>

        <% email_sender = email.from[0].mailbox << "@" << email.from[0].host %>
        <% email.from[0].name.blank? ? sender = email_sender :  sender = email.from[0].name %>

        <% receivers = [] %>
        <% if !email.to.blank? %>
          <% email.to.each do |recipient| %>
            <% email_receiver = recipient.mailbox << "@" << recipient.host %>
            <% recipient.name.blank? ? receivers << email_receiver :  receivers << recipient.name %>
          <% end %>
        <% end %>
        <% if !email.message.cc.blank? %>
          <% receivers << "CC: "%>
          <% email.message.cc.each do |cc| %>
            <% receivers << cc %>
          <% end %>
        <% end %>
        <% if !email.message.bcc.blank? %>
          <% email.message.bcc.each do |bcc| %>
            <% receivers << "#{bcc} " %>
          <% end %>
        <% end %>

        <div class = 'col-lg-4 col-md-4 col-sm-4 col-xs-4 data'>
          <span class = 'data'>
            <% receivers.each do |receiver| %>
              <%= "#{receiver} "%>
            <% end %>
          </span>
        </div>
        <% subject = email.message.subject %>
        <% if !subject.blank? %>
          <% if subject.include? "=?WINDOWS-1252?Q?" %>
          <% subject = subject.gsub!("=?WINDOWS-1252?Q?","").unpack("M").first.gsub('_',' ').force_encoding('WINDOWS-1252').encode('UTF-8')%>
          <% end %>
        <% else %>
          <% subject = "(No Subject)" %>
        <% end %>
        <div class = 'col-lg-6 col-md-6 col-sm-6 col-xs-6 data'>
          <span><%= subject %></span>
        </div>
        <div class = 'col-lg-2 col-md-2 col-sm-2 col-xs-2 data'>
          <% current_date = email.date.to_datetime.in_time_zone("Hong Kong") %>
          <span><%= current_date.to_date.today? ? current_date.strftime('%I:%M %p') : current_date.strftime('%b %e') %></span>
          <% if /Content-Disposition:\s*attachment/.match(email.raw_message.body.decoded) %>
          <span><%= fa_icon 'paperclip'  %></span>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
  <% end %>
  <%= will_paginate @unread, param_name: 'unread_page',  renderer: BootstrapPagination::Rails %>
<% else %>
  <span>You have no unread messages.</span>
<% end %>
<br>
  </div>
  <div class="tab-pane" id = 'read_tab'>
<% if @read_count > 0 %>
  <% @read.each do |email| %>
    <%= link_to display_message_path(id: email.uid, mailbox: 'sent') do%>
    <div class = 'row message-row'>
      <div class = 'col-md-12 col-lg-12 col-xs-12 col-sm-12'>

        <% email_sender = email.from[0].mailbox << "@" << email.from[0].host %>
        <% email.from[0].name.blank? ? sender = email_sender :  sender = email.from[0].name %>


        <% receivers = [] %>
        <% if !email.to.blank? %>
          <% email.to.each do |recipient| %>
            <% email_receiver = recipient.mailbox << "@" << recipient.host %>
            <% recipient.name.blank? ? receivers << email_receiver :  receivers << recipient.name %>
          <% end %>
        <% end %>
        <% if !email.message.cc.blank? %>
          <% receivers << "CC: "%>
          <% email.message.cc.each do |cc| %>
            <% receivers << cc %>
          <% end %>
        <% end %>
        <% if !email.message.bcc.blank? %>
          <% receivers << "BCC: "%>
          <% email.message.bcc.each do |bcc| %>
            <% receivers << bcc %>
          <% end %>
        <% end %>

        <div class = 'col-lg-4 col-md-4 col-sm-4 col-xs-4 data'>
          <span class = 'data'>
            <% receivers.each do |receiver| %>
              <%= "#{receiver} "%>
            <% end %>
          </span>
        </div>
        <% subject = email.message.subject %>
        <% if !subject.blank? %>
          <% if subject.include? "=?WINDOWS-1252?Q?" %>
          <% subject = subject.gsub!("=?WINDOWS-1252?Q?","").unpack("M").first.gsub('_',' ').force_encoding('WINDOWS-1252').encode('UTF-8')%>
          <% end %>
        <% else %>
          <% subject = "(No Subject)" %>
        <% end %>
        <div class = 'col-lg-6 col-md-6 col-sm-6 col-xs-6 data'>
          <span class = 'data'><%= subject %></span>
        </div>
        <div class = 'col-lg-2 col-md-2 col-sm-2 col-xs-2 data'>
          <% current_date = email.date.to_datetime.in_time_zone("Hong Kong") %>
          <span><%= current_date.to_date.today? ? current_date.strftime('%I:%M %p') : current_date.strftime('%b %e') %></span>
          <% if /Content-Disposition:\s*attachment/.match(email.raw_message.body.decoded) %>
          <span><%= fa_icon 'paperclip'  %></span>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
  <% end %>
    <%= will_paginate @read, param_name: 'read_page', renderer: BootstrapPagination::Rails %>
    <% else %>
    <span>You have not read any messages.</span>
    <% end %>
    <br>
  </div>
</div>

<script>
    $('#message_navigation a').click(function (e) {
        e.preventDefault()
        $(this).tab('show')
    });

    // store the currently selected tab in the hash value
    $("ul.nav-tabs > li > a").on("shown.bs.tab", function (e) {
        var id = $(e.target).attr("data-target").substr(1);
        window.location.hash = id;
    });

    // on load of the page: switch to the currently selected tab
    var hash = window.location.hash;
    $('#message_navigation a[data-target="' + hash + '"]').tab('show');
</script>
<% end %>